// GET /api/applications/[id]/download/[kind] — streams the file
// through with Content-Disposition: attachment. `kind` is 'cv' or
// 'cover_letter'. 410 Gone if the file expiry has passed.
//
// Previously this route 302-redirected to a Supabase signed URL.
// That worked for single clicks but broke parallel downloads (e.g.
// user clicks CV then immediately clicks Cover Letter): Chrome
// silently drops the `<a download>` semantic when an anchor's URL
// 302s to a different origin, falling back to a top-level
// navigation that gets converted into a download by Content-
// Disposition — and a second click cancels the in-flight first.
// Streaming through keeps everything same-origin, so the anchor's
// `download` attribute is honoured and clicks fire as independent
// subresource downloads. Files are ~30–80 KB so the extra hop
// through the Function is trivial bandwidth + memory.
//
// Filename per app_handoff §5.5:
//   {lastname}_CV_{company_short}_{yyyymmdd}.docx
//   {lastname}_CoverLetter_{company_short}_{yyyymmdd}.docx

import { NextResponse } from "next/server";
import { ApiError } from "@/lib/errors/api-error";
import { asSuccessOutput, buildFilename, type DocKind } from "@/lib/docx/filename";
import { withLogging } from "@/lib/logging/with-logging";
import { createClient } from "@/lib/supabase/server";
import { createServiceClient } from "@/lib/supabase/service";

const BUCKET = "generated";
const DOCX_MIME =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

type RouteCtx = { params: Promise<{ id: string; kind: string }> };

export async function GET(req: Request, ctxArg: RouteCtx) {
  const { id, kind } = await ctxArg.params;
  const inner = withLogging("applications.download", async (_, ctx) => {
    if (kind !== "cv" && kind !== "cover_letter") {
      throw new ApiError("invalid_request");
    }
    const userClient = await createClient();
    const { data: userData } = await userClient.auth.getUser();
    if (!userData.user) throw new ApiError("not_authenticated");
    ctx.user_id = userData.user.id;
    ctx.application_id = id;

    const { data: app } = await userClient
      .from("applications")
      .select(
        "id, status, cv_storage_path, letter_storage_path, files_expire_at, files_deleted_at, completed_at, llm_response_json",
      )
      .eq("id", id)
      .maybeSingle();
    if (!app) throw new ApiError("application_not_found");
    if (app.status !== "success") throw new ApiError("invalid_application_state");
    if (
      app.files_deleted_at ||
      (app.files_expire_at && new Date(app.files_expire_at).getTime() < Date.now())
    ) {
      throw new ApiError("files_expired");
    }

    const path =
      kind === "cv" ? app.cv_storage_path : app.letter_storage_path;
    if (!path) throw new ApiError("files_expired");

    const filename = buildFilename(
      kind as DocKind,
      asSuccessOutput(app.llm_response_json),
      app.completed_at ? new Date(app.completed_at) : new Date(),
    );

    const service = createServiceClient();
    const { data: blob, error: dlErr } = await service.storage
      .from(BUCKET)
      .download(path);
    if (dlErr || !blob) {
      throw new ApiError("storage_failed", dlErr?.message);
    }
    const buffer = await blob.arrayBuffer();

    // Filename is generated by buildFilename() which slugifies the
    // company_short to [A-Za-z0-9_] and capitalises the lastname —
    // safe for the quoted-string Content-Disposition form. RFC 5987
    // not needed.
    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type": DOCX_MIME,
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": String(buffer.byteLength),
        "Cache-Control": "private, no-store",
      },
    });
  });
  return inner(req as never);
}
